### ISSUE TITLE
DiscordJS 11.5 Update

### ISSUE THREAD

**Issue by ewang2002** [gideontong/Bot4Christ#3]
DiscordJS was recently updated to 11.5, which you can read more about here: https://github.com/discordjs/discord.js/releases/tag/11.5.0

**Comment by gideontong** [comment]
Bumped DiscordJS to 11.5 in commit [6e7200cd3ea08b26f1ff6ebea6357b484c079f12](https://github.com/gideontong/A4CDiscord/commit/6e7200cd3ea08b26f1ff6ebea6357b484c079f12).
